### ISSUE TITLE
AppCongif

### ISSUE THREAD

**Issue by coreyt808** [creativeaura/threesixty-slider#59]
First of all, thank you for making this threesixty code into a jquery plugin.

I'm not sure if you noticed, but the AppConfig is misspelled "AppCongif".  It's fine except it's spelled correctly/differently when getting playSpeed.  For example, line 316 uses AppConfig.playSpeed and causes an undefined error.

**Comment by creativeaura** [comment]
Fixed in v2.0.4

**Comment by coreyt808** [comment]
Hi,

Line 273 still has "AppConfig".  Throws an error when trying to run the play_stop function.

Thanks

**Comment by creativeaura** [comment]
Oh Yes, I didn't realise that ... fixed and pushed to v2.0.5
