### ISSUE TITLE
Filename prefixing request

### ISSUE THREAD

**Issue by rarewave** [creativeaura/threesixty-slider#63]
Hi, Great Plugin! I am looking at switching to this from another 360 plugin for one of my customers websites. The current plugin is experiencing some chrome / webkit issues so we have been searching for an alternative.

We already have around 800 product 360 folders and they are set out in following file format:

img01.jpg,
img02.jpg,
img03.jpg,
..
img09.jpg,
img10.jpg,
img11.jpg,

When applying the file prefix  "img". The output filename is img1.jpg (which doesn't exist).

When applying the file prefix "img0" the filename becomes img01.jpg which works for the first 9 frames, however once it reaches frame ten, it outputs, img010.jpg (again, doesn't exist).

I am wondering how feasible it is to add a further option to allow for a leading zero within the first 9 frames as it would be quite time consuming renaming all of the filenames on the server.

Thanks

**Comment by simonseddon** [comment]
Try using 'img' as the prefix and set option zeroPadding (or zeroBased) to true.

**Comment by rarewave** [comment]
Thankyou simonseddon, that has worked great, I had overlooked those options. Cheers
