### ISSUE TITLE
Wrong direction

### ISSUE THREAD

**Issue by fadifannoun** [creativeaura/threesixty-slider#77]
Hey 
I am using the default settings, but the motion direction is against the mouse. If I dragged it to the left the images rotate to right which is not user friendly!

Thanks

**Comment by yvestan** [comment]
Try this https://github.com/creativeaura/threesixty-slider/issues/70#issuecomment-107836908

**Comment by Slevender** [comment]
Thanks!

**Comment by fadifannoun** [comment]
Thanks
